// Generated by ReScript, PLEASE EDIT WITH CARE


function make(bits, name) {
  return new File(bits, name);
}

var $$File$1 = {
  make: make
};

function make$1(param) {
  return new FileReader();
}

var $$FileReader$1 = {
  make: make$1
};

export {
  $$File$1 as $$File,
  $$FileReader$1 as $$FileReader,
  
}
/* No side effect */
