// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BsFileDemo from "./BsFileDemo.bs.js";
import * as ReactDOMRe from "reason-react/lib/es6/src/legacy/ReactDOMRe.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(BsFileDemo.make, {}), "root");

export {
  
}
/*  Not a pure module */
