// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(bits, name) {
  return new File(bits, name);
}

var $$File$1 = {
  make: make
};

function make$1(param) {
  return new FileReader();
}

var $$FileReader$1 = {
  make: make$1
};

exports.$$File = $$File$1;
exports.$$FileReader = $$FileReader$1;
/* No side effect */
