// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var BsFileDemo = require("./BsFileDemo.bs.js");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(BsFileDemo.make, {}), "root");

/*  Not a pure module */
